from setuptools import setup, find_packages

setup(
  name="featherbot",
  version="0.0.1",
  license="MIT",
  author="Bailey de Villiers",
  author_email="bailey.devilliers@gmail.com",
  packages=find_packages("scripts"),
  package_dir={'': "scripts"},
  url='https://github.com/feather-marketing/featherbot',
  keywords="digital marketing",
  install_requires=[
    "async-generator",
    "attrs",
    "beautifulsoup4",
    "certifi",
    "charset-normalizer",
    "exceptiongroup",
    "h11",
    "idna",
    "numpy",
    "outcome",
    "packaging",
    "pandas",
    "PySocks",
    "python-dateutil",
    "python-dotenv",
    "pytz",
    "requests",
    "selenium",
    "six",
    "sniffio",
    "sortedcontainers",
    "soupsieve",
    "tqdm",
    "trio",
    "trio-websocket",
    "urllib3",
    "webdriver-manager",
    "wsproto"
  ],
)

